# 基础兼容
-
  font-size: 8
  dir-from: miseki-bitmap/0080-00FF Latin-1 Supplement
  glyph-scope: common
-
  font-size: 8
  dir-from: miseki-bitmap/0100-017F Latin Extended-A
  glyph-scope: common
-
  font-size: 8
  dir-from: miseki-bitmap/0180-024F Latin Extended-B
  glyph-scope: common
-
  font-size: 8
  dir-from: boutique-bitmap/2000-206F General Punctuation
  glyph-scope: common
-
  font-size: 8
  dir-from: boutique-bitmap/2150-218F Number Forms
  glyph-scope: common
-
  font-size: 8
  dir-from: miseki-bitmap/2200-22FF Mathematical Operators
  glyph-scope: common
-
  font-size: 8
  dir-from: miseki-bitmap/2460-24FF Enclosed Alphanumerics
  glyph-scope: common
-
  font-size: 8
  dir-from: miseki-bitmap/2600-26FF Miscellaneous Symbols
  glyph-scope: common
-
  font-size: 8
  dir-from: boutique-bitmap/3100-312F Bopomofo
  glyph-scope: common
-
  font-size: 8
  dir-from: boutique-bitmap/3200-32FF Enclosed CJK Letters and Months
  glyph-scope: common
-
  font-size: 8
  dir-from: galmuri/FE10-FE1F Vertical Forms
  glyph-scope: common
-
  font-size: 8
  dir-from: boutique-bitmap/FE30-FE4F CJK Compatibility Forms
  glyph-scope: common
-
  font-size: 8
  dir-from: boutique-bitmap/FE50-FE6F Small Form Variants
  glyph-scope: common
-
  font-size: 8
  dir-from: boutique-bitmap/FF00-FFEF Halfwidth and Fullwidth Forms
  glyph-scope: common


# 汉字
-
  font-size: 8
  dir-from: miseki-bitmap/4E00-9FFF CJK Unified Ideographs
  glyph-scope: common
  flavors: zh_hans
-
  font-size: 8
  dir-from: boutique-bitmap/4E00-9FFF CJK Unified Ideographs
  glyph-scope: common
  flavors: zh_hant,zh_hk,zh_tw
-
  font-size: 8
  dir-from: misaki/4E00-9FFF CJK Unified Ideographs
  glyph-scope: common
  flavors: ja
-
  font-size: 8
  dir-from: galmuri/4E00-9FFF CJK Unified Ideographs
  glyph-scope: common
  flavors: ko
-
  font-size: 10
  dir-from: boutique-bitmap/4E00-9FFF CJK Unified Ideographs
  glyph-scope: common
  flavors: zh_hant,zh_hk,zh_tw
-
  font-size: 10
  dir-from: galmuri/4E00-9FFF CJK Unified Ideographs
  glyph-scope: common
  flavors: ko
-
  font-size: 12
  dir-from: cubic-11/4E00-9FFF CJK Unified Ideographs
  glyph-scope: common
  flavors: zh_hant,zh_hk,zh_tw
-
  font-size: 12
  dir-from: galmuri/4E00-9FFF CJK Unified Ideographs
  glyph-scope: common
  flavors: ko


# 日语假名
-
  font-size: 8
  dir-from: misaki/3040-309F Hiragana
  glyph-scope: common
-
  font-size: 8
  dir-from: misaki/30A0-30FF Katakana
  glyph-scope: common


# 谚文
-
  font-size: 8
  dir-from: galmuri/3130-318F Hangul Compatibility Jamo
  glyph-scope: common
-
  font-size: 8
  dir-from: galmuri/AC00-D7AF Hangul Syllables
  glyph-scope: common
-
  font-size: 10
  dir-from: galmuri/AC00-D7AF Hangul Syllables
  glyph-scope: common
-
  font-size: 12
  dir-from: galmuri/AC00-D7AF Hangul Syllables
  glyph-scope: common
